---
- name: Prerequisites
  hosts: lbservers  
  tasks:
    - name: Pinging the host
      ping:
      
    - name: Install common resources
      hosts: all
      become: yes
      roles:
      - prerequisites

- name: HAProxy
  hosts: lbservers
  become: yes
  roles:
  - haproxy  
   tags:
  - haproxy